version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-14.7

    working_directory: /home/stackage/project

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - restore_cache:
          key: stack-blockchains-query-api-{{ checksum "stack.yaml" }}
      - restore_cache:
          key: stack-blockchains-query-api-final-{{ checksum "stack.yaml" }}
      - run: .circleci/setupenv.sh
      - run: stack build --only-dependencies -j1
      - save_cache:
          key: stack-blockchains-query-api-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - .stack-work
            - ~/.local
      - run: .circleci/build.sh
      - run: .circleci/test.sh
      - save_cache:
          key: stack-blockchains-query-api-final-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - .stack-work
            - ~/.local
      - run: .circleci/lint.sh
      - persist_to_workspace:
          root: ~/.local/bin/
          paths: 
            - blockchains-query-api
      - store_artifacts:
          path: ~/.local/bin
          destination: blockchains-query-api

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
